/*
Copyright 2019-2020 vChain, Inc.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
	http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package api

import (
	"github.com/grpc-ecosystem/grpc-gateway/runtime"
)

// Pattern_ImmuService_VerifiedGet_0 exposes the runtime Pattern need to overwrite VerifiedGet autogenerated request
func Pattern_ImmuService_VerifiedGet_0() runtime.Pattern {
	return runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2}, []string{"db", "verified", "get"}, "", runtime.AssumeColonVerbOpt(true)))
}

// Pattern_ImmuService_VerifiedSet_0 exposes the runtime Pattern need to overwrite VerifiedSet autogenerated request
func Pattern_ImmuService_VerifiedSet_0() runtime.Pattern {
	return runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2}, []string{"db", "verified", "set"}, "", runtime.AssumeColonVerbOpt(true)))
}

// Pattern_ImmuService_VerifiedSetReference_0 exposes the runtime Pattern need to overwrite VerifiedSetReference autogenerated request
func Pattern_ImmuService_VerifiedSetReference_0() runtime.Pattern {
	return runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2}, []string{"db", "verified", "setreference"}, "", runtime.AssumeColonVerbOpt(true)))
}

// Pattern_ImmuService_VerifiedZAdd_0 exposes the runtime Pattern need to overwrite VerifiedZAdd autogenerated request
func Pattern_ImmuService_VerifiedZAdd_0() runtime.Pattern {
	return runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2}, []string{"db", "verified", "zadd"}, "", runtime.AssumeColonVerbOpt(true)))
}

// Pattern_ImmuService_VerifiedTxById_0 exposes the runtime Pattern need to overwrite VerifiedTxById autogenerated request
func Pattern_ImmuService_VerifiedTxById_0() runtime.Pattern {
	return runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 1, 0, 4, 1, 5, 2}, []string{"db", "verified", "tx"}, "", runtime.AssumeColonVerbOpt(true)))
}
