name: CI
on: [push]
jobs:
  build-linux:
    name: Build
    strategy:
      matrix:
        go-version: [1.13]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - uses: actions/checkout@v1

      - name: Build
        run: make all

      - name: Test
        run: |
          make test
        shell: bash
  build-windows:
    name: Build
    strategy:
      matrix:
        go-version: [1.13]
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - uses: actions/checkout@v1

      - name: Build
        env:
          GO111MODULE: "on"
        run: make all
